[project]
name = "iterativennsimple"
version = "0.3.1"
description = "A simple version of iterativenn to get people started"
readme = "README.md"
requires-python = ">=3.10,<4.0"
authors = [{ name = "Randy Paffenroth", email = "rcpaffenroth@wpi.edu" }]
license = { text = "BSD 3-Clause License" }
dependencies = [
    "torch==2.5.1",
    "torchvision==0.20.*",
    "numpy==2.1.*",
    "pandas==2.2.*",
    "pyarrow==17.*",
    "matplotlib==3.9.*",
    "plotly==5.24.*",
    "ipykernel==6.29.*",
    "ipympl==0.9.*",
    "jupyterlab==4.3.*",
    "jupytext==1.17.*",
    "nbconvert==7.16.*",
    "scikit-learn==1.6.*",
    "wandb==0.19.*",
    "click==8.1.*",
    "papermill==2.6.0",
    "generatedata" 
]

[project.optional-dependencies]
dev = [
    "pytest==8.3.*",
    "pylint==3.2.*",
    "nbmake==1.5.*",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--nbmake"
testpaths = [
    "tests",
]

[tool.uv.sources]
generatedata = { git = "https://github.com/rcpaffenroth/generatedata.git", rev = "release/v0.3.2" }

[tool.uv]
default-groups = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
