"""Run one `lra_benchmark.py` cell per (dataset, step_size) and summarise the grid.

Usage:

    uv run python examples/lra_difficulty_ladder.py examples/lra_runs/difficulty_ladder

The directory holds one `config.yaml` carrying a `sweep:` block.  For each cell
this writes `<dataset>_step<N>/config.yaml` -- a plain, standalone config with no
`sweep:` key -- and calls `lra_benchmark.main` on it, so every cell keeps the
existing directory-in/files-out contract and can be re-run on its own:

    uv run python examples/lra_benchmark.py \\
        examples/lra_runs/difficulty_ladder/lra_image_step4

A cell whose `results.json` already exists is skipped, so a four-hour grid that
dies at cell 17 resumes instead of restarting.  Re-running once every cell is
done therefore does nothing but rewrite `summary.md`, which is the replot path.

`summary.md` reports and does not interpret (PRINCIPLES 1.3).  In particular it
does not compute a "spread" or nominate a winning cell: with five models at one
seed the largest spread over twenty cells is substantially selectable by noise.
The frontier -- the hardest cell at which our model still demonstrably learns --
is read off the table by eye, against the resolution quoted in each row.
"""

import json
import sys
from pathlib import Path

import yaml

from lra_benchmark import main as run_cell


def cell_config(cfg, dataset, step_size):
    """The standalone config for one cell: the shared blocks, specialised.

    Exactly two things vary across the grid -- the dataset name with its
    step_size, and the epoch budget, which cannot be shared across a ladder whose
    rungs converge at wildly different rates.  Everything else is copied
    unchanged, which is what makes a within-cell model comparison clean.
    """
    cell = {key: value for key, value in cfg.items() if key != 'sweep'}
    cell['dataset'] = {**cfg['dataset'],
                       'name': dataset['name'], 'step_size': step_size}
    cell['training'] = {**cfg['training'], 'epochs': dataset['epochs']}
    return cell


def dataset_facts(cfg, name):
    """`num_points`, `num_classes` and `x_y_index`, from generatedata's info file.

    Read from disk rather than by loading the data, because the summary needs
    only these three numbers and the rows are up to 40 MB.  Every dataset in this
    grid sets `local: true`, so the file is guaranteed to be beside the parquet.
    """
    data_dir = Path(cfg['dataset']['data_dir'])
    return json.loads((data_dir / f'{name}_info.json').read_text())


def write_summary(directory, cfg, cells):
    """One row per cell, one column per model, plus what each row can resolve."""
    names = [spec['name'] for spec in cfg['models']]

    lines = ['# Difficulty ladder — test accuracy across the grid', '',
             f'Generated by `examples/lra_difficulty_ladder.py` from '
             f'`{directory.name}/config.yaml`.', '',
             'Test accuracy is from the epoch with the best validation accuracy, '
             'one seed, `lr` 1e-3.',
             '',
             '`± res` is the smallest difference between two models in that row '
             'that the test split can resolve: '
             '$2\\sqrt{2}\\,\\sqrt{p(1-p)/n}$ at the row\'s best accuracy, '
             'floored at $3/n$ so a saturated row is not reported as exact. '
             'It counts evaluation sampling noise only — with one seed there is '
             'no measurement of seed-to-seed variation at all.',
             '',
             '**Cells are different tasks.** `step_size` sets both `seq_len` and '
             '`input_size`, so a comparison across rows is not controlled; only '
             'the comparison across columns *within* a row is.',
             '',
             '| dataset | step | seq_len | chance | ± res | '
             + ' | '.join(names) + ' |',
             '| --- | ---: | ---: | ---: | ---: | '
             + ' | '.join('---:' for _ in names) + ' |']

    for cell in cells:
        accuracies = [cell['results'].get(name, {}).get('test_acc') for name in names]
        finite = [a for a in accuracies if a is not None and a == a]  # a != a is NaN
        best = max(finite) if finite else float('nan')
        # sqrt(p(1-p)/n) collapses to zero at p = 1, which would print a
        # saturated row as infinitely precise.  The rule of three -- observing
        # zero errors in n trials still admits a rate up to about 3/n -- is the
        # right floor there, and is negligible away from the boundary.
        resolution = max(2 * (2 * best * (1 - best) / cell['n_test']) ** 0.5,
                         3.0 / cell['n_test'])

        # A diverged model is marked rather than shown as a number: it reached NaN
        # and its accuracy is undefined, which is not the same as "did badly".
        shown = []
        for name, accuracy in zip(names, accuracies):
            record = cell['results'].get(name, {})
            if accuracy is None or accuracy != accuracy:
                shown.append(f'DIVERGED@{record.get("diverged_at", "?")}')
            else:
                shown.append(f'{accuracy:.3f}')

        lines.append(
            f'| `{cell["dataset"]}` | {cell["step_size"]} | {cell["seq_len"]} | '
            f'{cell["chance"]:.3f} | {resolution:.3f} | ' + ' | '.join(shown) + ' |')

    lines += ['', '## Cells', '',
              'Each is a standalone run directory; `results.md` and `curves.png` '
              'are beside its `config.yaml`.', '']
    lines += [f'- `{cell["directory"]}` — {cell["epochs"]} epochs' for cell in cells]

    (directory / 'summary.md').write_text('\n'.join(lines) + '\n')


def main(directory):
    directory = Path(directory)
    cfg = yaml.safe_load((directory / 'config.yaml').read_text())

    cells = []
    for dataset in cfg['sweep']['datasets']:
        info = dataset_facts(cfg, dataset['name'])
        for step_size in cfg['sweep']['step_sizes']:
            cell_directory = directory / f'{dataset["name"]}_step{step_size}'
            cell_directory.mkdir(exist_ok=True)
            (cell_directory / 'config.yaml').write_text(
                yaml.safe_dump(cell_config(cfg, dataset, step_size),
                               sort_keys=False))

            if (cell_directory / 'results.json').exists():
                print(f'\n=== {cell_directory.name}: already done, skipping', flush=True)
            else:
                print(f'\n=== {cell_directory.name}', flush=True)
                run_cell(cell_directory)

            # The split arithmetic mirrors `lra_benchmark.load_task`, which takes
            # floors of the fractions and gives the remainder to test.
            n = info['num_points']
            n_test = n - int(cfg['dataset']['train_frac'] * n) \
                       - int(cfg['dataset']['val_frac'] * n)
            cells.append({
                'dataset': dataset['name'], 'step_size': step_size,
                'seq_len': info['x_y_index'] // step_size,
                'chance': 1.0 / info['num_classes'], 'n_test': n_test,
                'epochs': dataset['epochs'], 'directory': cell_directory.name,
                'results': json.loads((cell_directory / 'results.json').read_text()),
            })

    write_summary(directory, cfg, cells)
    print(f'\nwrote {directory / "summary.md"} over {len(cells)} cells')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(f'usage: {sys.argv[0]} <directory containing config.yaml>')
    main(sys.argv[1])
